name: interiorcreation
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/869ca70b-ff46-4044-b8ae-07ce496dffc6.jpg
layout_spectrum: 0.10193886351771653
typography_spectrum: 0.16739489091560245
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.7149378024041653
  lightness: 0.3977084052748978
  saturation: 0.8192461007274687
  rhythmicContrast: 0.0856713259126991
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
coverPrefs:
  filter: false
