name: interiorcreation
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/869ca70b-ff46-4044-b8ae-07ce496dffc6.jpg
layout_spectrum: 0.7479329803027213
typography_spectrum: 0.16739489091560245
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FF8000'
    - '#FFD933'
    - '#CCCC52'
    - '#8FB359'
    - '#192B33'
  brandStrength: 0.1279750249814242
  lightness: 0.32827712455764413
  saturation: 0.605010750470683
  rhythmicContrast: 0.1632707437966019
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
coverPrefs:
  filter: false
