name: interiorcreation
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/869ca70b-ff46-4044-b8ae-07ce496dffc6.jpg
layout_spectrum: 0.10193886351771653
typography_spectrum: 0.16739489091560245
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.8192453999072313
  lightness: 0.004300854634493589
  saturation: 0.5329787826631218
  rhythmicContrast: 0.526791162788868
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
coverPrefs:
  filter: false
